### ISSUE TITLE
BlackJack Assignment

### ISSUE THREAD

**Issue by rvaswani** [kevindeslauriers/Block-Five#3]
https://github.com/rvaswani/ICS3U/blob/master/BlackJack%20Final/src/com/bayviewglen/BlackJackFinal/BlackjackFinal.java

**Comment by justinborromeo** [comment]
Very nice!!!!

**Comment by justinborromeo** [comment]
Your code is very efficient

**Comment by mjennings2** [comment]
Why do I get emails for this

**Comment by justinborromeo** [comment]
Not sure

**Comment by kevindeslauriers** [comment]
Because you are following Rishi Justin and I bet Matt is following you!
