### ISSUE TITLE
Would like to see more challenging For Loop problems

### ISSUE THREAD

**Issue by justinborromeo** [kevindeslauriers/Block-Five#5]

**Comment by mjennings2** [comment]
doubtful

**Comment by mjennings2** [comment]
Write a for loop that loops as many times as the user is tall in mm by scanning their height using the computer's camera Mr. Waterloo mechatronics

**Comment by justinborromeo** [comment]
for(int i=0; i<cv2.getHeightInMm(); i++){
    foo();
}

**Comment by kevindeslauriers** [comment]
You can do better than that.

**Comment by justinborromeo** [comment]
Abstraction is one of the principles of OOP
